
services:
  depth:
    build: ./Cont
    container_name: depth
    ports:
      - "8888:8888"
    volumes:
          - ./Cont/Code:/app
  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility 


    ipc: host  

    ulimits:  
      memlock: -1
      stack: 67108864

    dns:
      - 8.8.8.8  
      - 8.8.4.4
    
    